uart:
  id: uart_gps
  baud_rate: 9600
  rx_pin: 22

# https://esphome.io/components/gps.html
gps:
  uart_id: uart_gps
  update_interval: 15s
#    altitude:
#      name: Altitude
#      icon: mdi:image-filter-hdr
#    course:
#      name: Course
#      icon: mdi:navigation

  <<: !include ../gps/latitude.yaml
  <<: !include ../gps/longitude.yaml
  <<: !include ../gps/satellites.yaml
  <<: !include ../gps/speed.yaml
