text_sensor:
  - platform: ble_client
    ble_client_id: shimano
    service_uuid: '180A'
#    type: characteristic
    characteristic_uuid: '2A25'
    name: "${friendly_name} BLE Device Serial Number"
    entity_category: diagnostic
#    icon: 'none'
