sensor:
  - platform: ble_client
    ble_client_id: bakfiets
    service_uuid: '180F'
    type: characteristic
    characteristic_uuid: '2A19'
    name: Battery Level
    unit_of_measurement: '%'
    device_class: battery
