binary_sensor:
  - platform: template
    name: ${friendly_name} BLE Device Status
    id: ble_status
    device_class: connectivity
    entity_category: diagnostic

esphome:
  on_boot:
    then:
      - binary_sensor.template.publish:
          id: ble_status
          state: false
