sensor:
  # https://esphome.io/components/sensor/dht.html
  - platform: dht
    model: DHT11
    pin: 22
    temperature:
      name: Temperature
    humidity:
      name: Humidity
    update_interval: 30s
