# M5 Atom neopixel led on the button
light:
  - platform: neopixelbus
    pin: GPIO27
    num_leds: 1
    variant: SK6812
    type: GRB
    id: status_led
    name: Status LED
    restore_mode: ALWAYS_OFF
