# ESP32-CAM
esp32_camera:
  name: ${friendly_name}
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  #reset_pin: GPIO32
  vertical_flip: true
  horizontal_mirror: true
  max_framerate: 0.5 fps
  idle_framerate: 0.1 fps
  resolution: 1024x768
  #resolution: 800x600
  #resolution: 640x480
  #jpeg_quality: 30
  jpeg_quality: 10
  contrast: 1
  brightness: 2
  saturation: 0
