substitutions:
  comment: ''

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${comment}

# ESPHome API configuration
api:
  encryption:
    key: !secret esphome_api_encryption_key

# Over-the-air update
ota:
  #password: !secret esphome_ota_password

# Sync time with HA
time:
  - platform: homeassistant

# Logging
logger:
